name = "after-dark"
description = "a fork of Vincent Prouillet's after-dark by Sharif Haason"
license = "MIT"
homepage = "https://sharifhsn.github.io"
min_version = "0.15.0"

[extra]

[author]
name = "Sharif Haason"
homepage = "https://sharifhsn.github.io"

[original]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"
repo = "https://github.com/getzola/after-dark"
